[package]
name = "rat-client"
edition = "2024"
version = "0.1.0"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.30.0"
ratback = { version = "0.1.1", path = "../backend" }
reqwest = {version = "0.13.2", features = ["blocking"]} 
serde = "1.0.228"
serde_json = "1.0.149"
